export const RECOMMENDATIONS = {
  "Apple___Apple_scab": "Apply fungicides like mancozeb or captan early in the season. Prune infected branches and remove fallen leaves.",
  "Apple___Black_rot": "Remove mummified fruits and infected twigs. Apply a copper-based fungicide before and after rainfall.",
  "Apple___Cedar_apple_rust": "Eliminate nearby juniper trees. Apply fungicides containing myclobutanil or propiconazole.",
  "Apple___healthy": "Healthy! Maintain pruning and proper air circulation to prevent fungal infection.",
  "Blueberry___healthy": "Healthy! Ensure soil acidity (pH 4.5–5.5) and avoid waterlogging.",
  "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur-based sprays. Prune for better airflow and avoid overhead watering.",
  "Cherry_(including_sour)___healthy": "Healthy! Keep trees well-spaced and water at the base, not the leaves.",
  "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Rotate crops yearly. Apply fungicides like azoxystrobin when lesions first appear.",
  "Corn_(maize)___Common_rust_": "Use resistant hybrids and apply fungicides at the tasseling stage.",
  "Corn_(maize)___Northern_Leaf_Blight": "Use resistant seeds. Apply foliar fungicides if disease pressure is high.",
  "Corn_(maize)___healthy": "Healthy! Continue good field hygiene and balanced nitrogen fertilization.",
  "Grape___Black_rot": "Prune infected vines and apply fungicides like mancozeb before rainfall.",
  "Grape___Esca_(Black_Measles)": "Remove affected wood. Avoid pruning during wet conditions.",
  "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Use copper fungicides and remove diseased leaves to reduce spore load.",
  "Grape___healthy": "Healthy! Maintain open canopy and periodic sulfur sprays to prevent powdery mildew.",
  "Orange___Haunglongbing_(Citrus_greening)": "Remove and destroy infected trees. Control psyllid insects using imidacloprid or neem oil.",
  "Peach___Bacterial_spot": "Use copper-based bactericides and ensure trees are not water-stressed.",
  "Peach___healthy": "Healthy! Prune regularly and fertilize to promote strong growth.",
  "Pepper,_bell___Bacterial_spot": "Use pathogen-free seeds and copper fungicides. Avoid overhead irrigation.",
  "Pepper,_bell___healthy": "Healthy! Maintain spacing and apply balanced fertilizers regularly.",
  "Potato___Early_blight": "Rotate crops, remove debris, and apply chlorothalonil-based fungicides.",
  "Potato___Late_blight": "Remove infected plants immediately. Apply mancozeb or metalaxyl-based fungicides.",
  "Potato___healthy": "Healthy! Ensure proper watering and pest management.",
  "Raspberry___healthy": "Healthy! Maintain good airflow between canes and use mulch to retain soil moisture.",
  "Soybean___healthy": "Healthy! Avoid excessive nitrogen and rotate crops with cereals.",
  "Squash___Powdery_mildew": "Use sulfur or potassium bicarbonate sprays and improve ventilation.",
  "Strawberry___Leaf_scorch": "Remove old leaves and apply fungicides containing captan or thiophanate-methyl.",
  "Strawberry___healthy": "Healthy! Keep soil moisture consistent and avoid leaf wetness.",
  "Tomato___Bacterial_spot": "Apply copper-based sprays and remove infected foliage. Avoid water splash on leaves.",
  "Tomato___Early_blight": "Prune lower leaves and apply chlorothalonil-based fungicides regularly.",
  "Tomato___healthy": "Healthy! Maintain spacing, apply organic mulch, and avoid overwatering.",
  "Tomato___Late_blight": "Remove infected plants. Apply mancozeb or copper oxychloride-based fungicides.",
  "Tomato___Leaf_Mold": "Reduce humidity and improve airflow in greenhouses. Use resistant varieties.",
  "Tomato___Septoria_leaf_spot": "Use fungicides containing copper hydroxide or mancozeb. Remove debris after harvest.",
  "Tomato___Spider_mites Two-spotted_spider_mite": "Spray neem oil or miticides. Maintain humidity above 50%.",
  "Tomato___Target_Spot": "Apply fungicides with azoxystrobin or mancozeb. Remove old leaves.",
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies and remove infected plants. Use virus-resistant hybrids.",
  "Tomato___Tomato_mosaic_virus": "Disinfect tools and avoid tobacco handling near plants. Remove infected plants.",
  "Tomato___healthy": "Healthy! Continue fertilizing and maintain pest-free conditions."
};
